name: customBosses
version: '1.0-SNAPSHOT'
main: me.iron_fist222.custombosses.CustomBosses
api-version: '1.20'
permissions:
  customBosses.bossSummoning:
    description: allows you to summon bosses from the customBosses plugin
    default: op
commands:
  SummonWaterBoss:
    description: Summons water boss from customBosses plugin
    usage: / <command>
    permission: customBosses.bossSummoning
  TestMove1:
    description: test move 1
    usage: / <command>
  TestMove2:
    description: test move 2
    usage: / <command>
  TestMove3:
    description: test move 3
    usage: / <command>
